name: "Deploy React to GitHub Pages"
description: "Action to automatically deploy ypur React code to GithHub Pages on push."
author: "amitsingh-007"
branding:
  color: "purple"
  icon: "cloud-lightning"

run:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
    - run: git --work-tree build add --all
      shell: bash
    - run: git --work-tree build commit -m 'deploy files'
      shell: bash
    - run: git push origin HEAD:gh-pages --force
      shell: bash
